# Generated by Django 3.0.2 on 2020-04-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GOU', '0002_auto_20200115_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=10)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
